from selenium.webdriver.common.by import By

class LoginPageLocators:
    WELCOME_WORDS = (By.CSS_SELECTOR, "[class*='registration_panelTitle']")
    DROPDOWN_BUTTON = (By.CSS_SELECTOR, "[class*='AccountSwitch_changeAccountName']")
    CURRENT_LK = (By.CSS_SELECTOR, "[class*='SimpleCell__after']")
    COPY_ID = (By.CSS_SELECTOR, "[class*='AccountSwitchListItem_userIdInner']")
    REGISTRATION_BUTTON = (By.CSS_SELECTOR, "[class*='ButtonCabinet_primary']")
    REGISTRATION_MODAL = (By.CLASS_NAME, "vkc__AuthRoot__contentIn")
    NAME = (By.CLASS_NAME, "vkc__LoginConnectOrPhone__caption")
    PROFILE_CREATION = (By.CLASS_NAME, "vkuiImageBase__children")
    COPY_TEXT = (By.CSS_SELECTOR, "[class*='AccountSwitchListItem_userIdCopy']")
    RUSSIAN_SELECT = (By.XPATH, '//div[@id="registration"]/div/div[2]/div/section/div/div/label/h4')
    ENGLISH_SELECT = (By.XPATH, '//div[@id="registration"]/div/div[2]/div/section/div/div/label[2]/h4')
    CREATE_NEW_BUTTON = (By.XPATH, '//div[@id="click-createNewButton"]/p')
    TITLE_NEW = (By.CLASS_NAME, 'HeaderNav_headerFormTitle')
    COUNTRY_SELECT = (By.NAME, 'country')
    CURRENCY_SELECT = (By.NAME, 'currency')
    ADS_TYPE = (By.CSS_SELECTOR, '#registration.new label:first-child > div > div > div')
    MAILING_CHECKBOX = (By.CSS_SELECTOR, '#registration.new label:nth-of-type(10) div[role="checkbox"]')
    EMAIL_INPUT = (By.NAME, 'email')
    INN_INPUT = (By.NAME, 'inn')
    COUNTRY_SELECT_BUTTON = (By.XPATH, '//input[@value=""]')
    COUNTRY_SELECT_RUSSIA = (By.XPATH, '//div[@id=":r2:-1"]')
    COUNTRY_SELECT_BELARUS = (By.XPATH, '//div[@id=":r2:-3"]')
    COUNTRY_SELECT_KAZAKHSTAN = (By.XPATH, '//div[@id=":r2:-4"]')
    COUNTRY_SELECT_TAJIKISTAN = (By.XPATH, '//div[@id=":r2:-16"]')
    CURRENCY_SELECT_BUTTON = (By.CSS_SELECTOR, '#registration.new input[name="currency"]')
    CURRENCY_SELECT_RUB = (By.CSS_SELECTOR, 'div[id*="-RUB"]')
    IND_TYPE = (By.CSS_SELECTOR, '#registration.new input[name="individualType"] + span')
    NAME_INPUT = (By.NAME, 'name')
    AGENCY_TYPE = (By.CSS_SELECTOR, '#registration.new label:nth-of-type(2) > div > div > div')
    LEGAL_TYPE = (By.CSS_SELECTOR, '#registration.new input[name="legalType"] + span')
    MAILING_CHECKBOX_LEGAL = (By.CSS_SELECTOR, '#registration.new label:nth-of-type(8)')
    ALERT_CONTAINER = (By.XPATH, '//span[@role="alert"]')
    SUBMIT_BUTTON = (By.XPATH, '//button[@type="submit"]')
